# Phoenix Template Development environment
# Docker compose meant for development environment
version: "3.8"
services:
  mysql.local:
    image: mysql:5.7.24
    logging:
      driver: none
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vagrant
    volumes:
      - foodguruapi.mysql:/var/lib/mysql
      - ./docker/config/sql:/docker-entrypoint-initdb.d

  phoenix_template:
    build:
      context: .
    image: fastcomm/phoenix_template:dev
    ports:
      - "4100:4100"
    depends_on:
      - mysql.local
    volumes: # Only edit this is you know exactly what you are doing. Order matters.
      - ./:/home/fc_user/phoenix_template # Bind volume to hot reload source code
      - phoenix_template.deps:/home/fc_user/phoenix_template/deps/ # Volume to persist dependencies. DON'T FORGET THE TRAILING SLASH!
      - phoenix_template.build:/home/fc_user/phoenix_template/_build/ # Volume to persist dependency artifacts. DON'T FORGET THE TRAILING SLASH!

volumes:
  fastcomm.mysql:
  phoenix_template.deps:
  phoenix_template.build:
