# Phoenix Template Development environment
# Docker compose meant for development environment
version: "3.8"

services:
  postgres.local:
    image: postgres:14.1-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: letmein
      POSTGRES_USER: postgres
      POSTGRES_DB: lula
    volumes:
      - readable_api.postgres:/var/lib/postgresql/data


  readable_api:
    build:
      context: .
    image: raymond/readable_api:dev
    ports:
      - "4100:4100"
    depends_on:
      - postgres.local
    volumes: # Only edit this is you know exactly what you are doing. Order matters.
      - ./:/home/fc_user/readable_api # Bind volume to hot reload source code
      - readable_api.deps:/home/fc_user/readable_api/deps/ # Volume to persist dependencies. DON'T FORGET THE TRAILING SLASH!
      - readable_api.build:/home/fc_user/readable_api/_build/ # Volume to persist dependency artifacts. DON'T FORGET THE TRAILING SLASH!

volumes:
  readable_api.postgres:
  readable_api.deps:
  readable_api.build:
