# Phoenix Template Development environment
# Docker compose meant for development environment
version: "3.8"
services:
  mysql.local:
    image: mysql:5.7.24
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: vagrant
    ports:
      - "3307:3306"  
    volumes:
      - readable_api.mysql:/var/lib/mysql
      - ./docker/config/sql:/docker-entrypoint-initdb.d

  loadbalancer:
    image: nginx:1.19.7
    logging:
      driver: none
    ports:
      - "80:80"
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - readable_api


  readable_api:
    build:
      context: .
    image: fastcomm/readable_api:dev
    ports:
      - "4100:4100"
    depends_on:
      - mysql.local
    volumes: # Only edit this is you know exactly what you are doing. Order matters.
      - ./:/home/fc_user/readable_api # Bind volume to hot reload source code
      - readable_api.deps:/home/fc_user/readable_api/deps/ # Volume to persist dependencies. DON'T FORGET THE TRAILING SLASH!
      - readable_api.build:/home/fc_user/readable_api/_build/ # Volume to persist dependency artifacts. DON'T FORGET THE TRAILING SLASH!

volumes:
  readable_api.mysql:
  readable_api.deps:
  readable_api.build:
